### ISSUE TITLE
 File "D:\anaconda3\envs\gupiao\lib\site-packages\pandas\core\indexes\base.py", line 6251, in _raise_if_missing     raise KeyError(f"{not_found} not in index") KeyError: "['EPS', 'Revenue', 'ROE', 'P/E'] not in index" Error fetching financial metrics: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

### ISSUE THREAD

**Issue by lmj282371** [harshitt13/Stock-Market-Prediction-Model#2]
This is the error that occurred when running fetch_data.py. How should it be resolved?

**Comment by harshitt13** [comment]
I kindly ask for some time to resolve these issues. I have a remote job that I work on daily, and I have also been attending classes since I was a college student. Additionally, I need to prepare for an upcoming hackathon, and my exams are approaching. On top of that, I must complete my college projects and assignments before the exams begin. 

I am currently going through a difficult period in my life, and it's challenging for me to stay motivated. Some days, I find it hard to get out of bed; I often stare at the white ceiling and feel exhausted.

Apologies for the inconvenience caused. To be honest, this project was meant to be a group effort, but everyone abandoned me, and now I have to complete it on my own. I hope you understand.

Thanks for understanding.

**Comment by harshitt13** [comment]
Hey,
Thanks for your patience and understanding. I have updated the code. I hope your issues have been resolved.

Harshit Kushwaha
